### ISSUE TITLE
我这边提示图形验证码错误，请重新输入

### ISSUE THREAD

**Issue by HF0920** [Cluas/189checkin#19]
请问是我的环境配置问题吗 还是请求过于频繁

**Comment by HF0920** [comment]
共有 1 个账号，即将开始签到
图形验证码错误，请重新输入
Traceback (most recent call last):
  File "checkin.py", line 147, in <module>
    helper.check_in()
  File "checkin.py", line 23, in check_in
    self.login()
  File "checkin.py", line 101, in login
    redirect_url = r.json()["toUrl"]
KeyError: 'toUrl'
Error: Process completed with exit code 1.
这是log...

**Comment by pzghost** [comment]
python3 checkin.py 
图形验证码错误，请重新输入
Traceback (most recent call last):
  File "checkin.py", line 147, in <module>
    helper.check_in()
  File "checkin.py", line 23, in check_in
    self.login()
  File "checkin.py", line 101, in login
    redirect_url = r.json()["toUrl"]
KeyError: 'toUrl'

**Comment by jneeee** [comment]
图形验证码错误，一般是账户被风控。尝试手动在app登录成功一次，再用脚本试
