### ISSUE TITLE
请问图形验证码错误怎么解决？没有设备锁，账号密码确认过是对的

### ISSUE THREAD

**Issue by JohnsonTam9527** [Cluas/189checkin#4]
报错信息
`共有 1 个账号，即将开始签到
图形验证码错误，请重新输入
Traceback (most recent call last):
  File "checkin.py", line 146, in <module>
    helper.check_in()
  File "checkin.py", line 22, in check_in
    self.login()
  File "checkin.py", line 100, in login
    redirect_url = r.json()["toUrl"]
KeyError: 'toUrl'
Error: Process completed with exit code 1.`

**Comment by y377** [comment]
换一个ip，不建议用云服务器（因为固定ip）
