### ISSUE TITLE
有图形验证了

### ISSUE THREAD

**Issue by lq-259** [Cluas/189checkin#8]
图形验证码错误，请重新输入
Traceback (most recent call last):
  File "checkin.py", line 146, in <module>
    helper.check_in()
  File "checkin.py", line 22, in check_in
    self.login()
  File "checkin.py", line 100, in login
    redirect_url = r.json()["toUrl"]
KeyError: 'toUrl'

**Comment by bawanag** [comment]
同问，好像脚本用不了了

**Comment by yaotutu** [comment]
同问。
图形验证码错误，请重新输入
Traceback (most recent call last):
  File "checkin.py", line 147, in <module>
    helper.check_in()
  File "checkin.py", line 23, in check_in
    self.login()
  File "checkin.py", line 101, in login
    redirect_url = r.json()["toUrl"]
KeyError: 'toUrl'
